[Settings]

# Lines starting with "#" are ignored.

##############################################
# TOGGLE BUTTON:			     #
# Used to toggle the ingame menu of ACPRIM   #
# Valid buttons are F-keys beetween F1 - F12 #
##############################################
ToggleButton = F1

######################################################
# TOGGLE ONLINE WINDOW BUTTON:			     #
# Used to toggle the Online info and settings window #
# Valid buttons are F-keys beetween F1 - F12 	     #
######################################################
ToggleOnlineButton = F2

######################################################
# TOGGLE OVERLAY WINDOW BUTTON:			     #
# Used to toggle the hitbox overlay and frame meter  #
# Valid buttons are F-keys beetween F1 - F12   	     #
######################################################
ToggleOverlayButton = F3

######################################################
# TOGGLE FRAME METER LEGEND BUTTON:		     #
# Used to toggle the legend for frame meter entries  #
# Valid buttons are F-keys beetween F1 - F12         #
######################################################
ToggleFrameMeterLegend = F4

######################################################
# TOGGLE HITSTUN DECAY AND RECOVERY METERS BUTTON:   #
# Used to toggle hitstun decay and recovery meters   #
# Valid buttons are F-keys beetween F1 - F12         #
######################################################
ToggleHSDMeters = F5

######################################################
# TOGGLE FRAME METER BUTTON:			     #
# Used to toggle hitstun decay and recovery meters   #
# Valid buttons are F-keys beetween F1 - F12         #
######################################################
ToggleFrameMeter = F6

######################################################
# TOGGLE GAME PAUSE BUTTON:			     #
# Used to pause and unpause the game 		     #
# Valid buttons are F-keys beetween F1 - F12         #
######################################################
ToggleGamePause = F7

######################################################
# FRAME STEP BUTTON:			     	     #
# Used to step one frame forward when game is paused #
# Valid buttons are F-keys beetween F1 - F12         #
######################################################
FrameStep = F8

###############################################################
# SAVE CBR BUTTON:				  	      #
# Used to save AI data after matches outside of training mode #
# Valid buttons are F-keys beetween F1 - F12  		      #
###############################################################
SaveCBRbutton = F9

##################################################################
# Discard CBR BUTTON:				  		 #
# Used to discard AI data after matches outside of training mode #
# Valid buttons are F-keys beetween F1 - F12	  		 #
##################################################################
DiscardCBRbutton = F10

#########################################
# MENUSIZE SETTINGS:			#
# Changes the size of ACPRIM's menu	#
# 1 = Small				#
# 2 = Medium				#
# 3 = Large				#
#########################################
MenuSize = 2

#######################################################################################
# NOTIFICATION SETTINGS:							      #
# Mainly used to notify about other ACPRIM users and their requests in online matches #
# Notifications are always shown on top of the window				      #
# 0 = off				     					      #
# 1 = on									      #
#######################################################################################
Notifications = 1

######################################################################
# CHECK UPDATES: 						     #
# Check and notify the user if a new version of ACPRIM is available  #
# Not currently used.                    			     #
# 0 = off							     #
# 1 = on							     #
######################################################################
CheckUpdates = 1

#############################################################################
# Steam DLL type:							    #
# If using the original steam_api.dll, set this to 0.                       #
# If using Goldberg's steam emulator or proton, set this to 1.              #
# Using the wrong setting will result in the game crashing when entering    #
# online lobby.                                                             #
#############################################################################
SteamDLLType = 0

#############################################################################
# DINPUT DLL CHAINING:							    #
# If you want to use another dinput8.dll wrapper together with ACPRIM,	    #
# rename the other dll (e.g. "dinputwrapper.dll") and put the new name here #
# Example:								    #
# DinputDllWrapper = dinputwrapper.dll					    #
#############################################################################
DinputDllWrapper = none

################################################################################
# INPUT BRIDGE								       #
# If running on a windows emulator on android such as Winlator / Mobox / etc...#
# will automatically run input bridge when opening the app.		       #
# Enter the path for the ib.exe executable.				       #
# Can also close input bridge when application closes.			       #
################################################################################
InputBridgeExec = none
CloseIBOnShutdown = 0

#############################################################################
# Skip state checks during replay					    #
# This is only useful when running on a windows emulator on android, which  #
# causes state mismatch errors during replays.				    #
# This skips the check enabling the replay to continue.			    #
#############################################################################
DisableStateMismatch = 0

[Overlay]

# Displays two bars that visualize hit stun decay and untech time
DisplayHSDMeter = 1

# Displays the frame meter
DisplayFrameMeter = 1

# If enabled, draws boxes that indicate a player's throw range
AlwaysDrawThrowRange = 0

# If enabled, frame meter continues when one of the characters is in a hitstop state
RecordDuringHitstop = 0

# If enabled, frame meter continues when one of the characters is in a superflash state
RecordDuringSuperflash = 0

# If enabled, frame meter will store previous game states to allow rewinding during replay mode
# Results in a slightly increased memory usage (~100 Mb)
AllowRewindingInReplay = 0

# If enabled, draws range boxes vertically over the entire screen
DrawInfiniteHeight = 0

[Overlay.Misc]
# Thickness of hitbox frames (should be between 0 and 5)
BorderThickness = 2.5

# Fill transparency of hitboxes (should be between 0 and 1)
FillTransparency = 0.5

# Size of cross showing player and entity positions
PivotSize = 15
PivotThickness = 3

# Coordinates expressed in normalized viewport coordinates (which are then fit to the game area so widescreen is not a factor)
# e.g. (-1.0, -1.0) is bottom left, (1.0, 1.0) is top right, (0, 0) is center
HSDMeterXPosition = -0.95
HSDMeterYPosition = 0.1

[Overlay.Palette]
# Colors in ARGB packed hexadecimal format i.e. 0xAARRGGBB. "0x" required.
#Hitbox palettes
Color_Hitbox         = 0xFFFF0000
Color_Hurtbox        = 0xFF00FF00
Color_Pushbox        = 0xFF00FFFF
Color_Grabbox        = 0xFFFF00FF
Color_CleanHit       = 0xFFFF8000
# For range check boxes such as Faust's Hack'n'Slash or Potemkin's Hammerfall activation range. (Similar to throw checks)
Color_MiscPushRange  =0xFFFF00FF
# For range check boxes that look for origin point position instead of pushbox edges (Similar to Sol's Clean Hit check)
Color_MiscPivotRange = 0xFFFF8000
Color_Pivot          = 0xFF800080

#Frame meter palettes
Color_Neutral          = 0xFF1B1B1B
Color_Movement         = 0xFF41F8FC
Color_CounterHitState  = 0xFF01B597
Color_Startup          = 0xFF01B597
Color_Active           = 0xFFCB2B67
Color_ActiveThrow      = 0xFFCB2B67
Color_Recovery         = 0xFF006FBC
Color_BlockStun        = 0xFFC8C800
Color_HitStun          = 0xFFC8C800
Color_TechableHitstun  = 0xFF969600
Color_KnockDownHitstun = 0xFF969600

#Primary frame properties
Color_InvulnFull     = 0xFFFFFFFF
Color_InvulnStrike   = 0xFF0080FF
Color_InvulnThrow    = 0xFFFF8000
Color_Parry          = 0xFF785000
Color_GuardPointFull = 0xFF785000
Color_GuardPointHigh = 0xFF785000
Color_GuardPointLow  = 0xFF785000
Color_Armor          = 0xFF785000
Color_SlashBack      = 0xFFFF0000

#Secondary frame properties
Color_FRC = 0xFFFFFF00

#HSD meter palettes
UntechMeterColor = 0xFF00FFFF
